// import層
import React, { ChangeEventHandler, memo, MouseEventHandler } from "react";
import styles from "../styles/Home.module.css";
import { signinUsecase } from "../application/usecase/signinUsecase";

// type層
type ContainerProps = {
  email: string;
  password: string;
  handleChangeEmail: ChangeEventHandler<HTMLInputElement>;
  handleChangePassword: ChangeEventHandler<HTMLInputElement>;
  signin: MouseEventHandler<HTMLInputElement>;
};

type Props = Required<ContainerProps>;

// DOM層
const Component: React.FC<Props> = (props) => (
  <div className={styles.container}>
    <title>signin</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <p>signin</p>
    <input type="text" value={props.email} onChange={props.handleChangeEmail} />
    <input
      type="password"
      value={props.password}
      onChange={props.handleChangePassword}
    />
    <button onClick={props.signin}>hoge</button>
  </div>
);

// Container層
const Container: React.FC<ContainerProps> = (props) => {
  const { email, password, handleChangeEmail, handleChangePassword, signin } =
    signinUsecase();
  return (
    <Component
      email={email}
      password={password}
      handleChangeEmail={handleChangeEmail}
      handleChangePassword={handleChangePassword}
      signin={signin}
    ></Component>
  );
};

export default memo(Container);
