import Head from "next/head";
import styles from "../styles/Home.module.css";
import { signinUsecase } from "../application/usecase/signinUsecase";

export default function Home() {
  const { email, password, handleChangeEmail, handleChangePassword, signin } =
    signinUsecase();

  return (
    <div className={styles.container}>
      <Head>
        <title>signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>signin</p>
      <input type="text" value={email} onChange={handleChangeEmail} />
      <input type="password" value={password} onChange={handleChangePassword} />
      <button onClick={signin}>hoge</button>
    </div>
  );
}
